export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const SEND_RAPPORT = "SEND_RAPPORT";
export const SEND_RAPPORT_SUCCESS = "SEND_RAPPORT_SUCCESS";
export const SEND_RAPPORT_FAILER = "SEND_RAPPORT_FAILER";

export const SAVE_RAPPORT = "SAVE_RAPPORT";
export const SAVE_RAPPORT_SUCCESS = "SAVE_RAPPORT_SUCCESS";
export const SAVE_RAPPORT_FAILER = "SAVE_RAPPORT_FAILER";

export const GET_RAPPORT = "GET_RAPPORT";
export const GET_RAPPORT_SUCCESS = "GET_RAPPORT_SUCCESS";
export const GET_RAPPORT_FAILER = "GET_RAPPORT_FAILER";




